github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://github.com/serpapps/loom-video-downloader",
"https://serpdownloaders.com/loom-video-downloader",
"https://serpapps.github.io/loom-video-downloader",
"https://devinschumacher.com/loom-video-downloader"
]
