github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://github.com/serpapps/vimeo-video-downloader",
"https://serpdownloaders.com/vimeo-video-downloader",
"https://serpapps.github.io/vimeo-video-downloader",
"https://devinschumacher.com/vimeo-video-downloader"
]
